### ISSUE TITLE
Missing part of Dataset

### ISSUE THREAD

**Issue by wanghao-cv** [DurrLab/C3VD#13]
Dear author 
Thanks to ur awesome work at first!
It seems that there is a missing part of the [cecum_t3_a.zip](http://drive.google.com/uc?export=view&id=1TqEZc4k_SNYDM2pN-vQmXVyLoAPqasRw&confirm=t)
I find some images are lost as followed screen-shot ,starts from 0671 to end  in cecum_t3_a video
![屏幕截图 2024-01-07 005356](https://github.com/DurrLab/C3VD/assets/72639364/ef6d8d99-f510-49f7-b7ac-edcb10306692)
![屏幕截图2024 01 07_01 01 25](https://github.com/DurrLab/C3VD/assets/72639364/10bb5dd3-0772-4515-a986-e73114c6704a)

**Comment by leeve818** [comment]
Same issue here. Also missing depth.tiff and normal.tiff from num 672 to num 729. 
And the occlusion.png seems to be damaged since num 671.

**Comment by tbobrow1** [comment]
@wanghao-cv & @leeve818 - thanks for bringing this to my attention! Something must have happened when compressing the final version of this sequence. I will recompress and upload the sequence this afternoon. Look for a reply here when it is live.

Please let me know if you notice any compression problems in the other sequences.

**Comment by tbobrow1** [comment]
@wanghao-cv & @leeve818 - I have uploaded the new compressed folder for cecum_t3_a to the dataset webpage. Please let me know if everything looks correct when you open it.

**Comment by leeve818** [comment]
@tbobrow1 - Thanks for your quick response. I downloaded the new compressed data and tested it. The issue has been resolved.
