### ISSUE TITLE
Photometry calibration

### ISSUE THREAD

**Issue by Ruyi-Zha** [DurrLab/C3VD#14]
Hi, thanks for the dataset. I noticed the provided calibration file is only about the camera (geometry). Is the light srouce (photometry) also calibrated? Could you provide the calibration results of the photometric model, e.g., spread factor, gamma response, etc.?

**Comment by tbobrow1** [comment]
Hi @Ruyi-Zha - we did not calibrate the photometry when recording the dataset. If you require these parameters, it may be possible to substitute the parameters included in the Endomapper dataset ( _[Endomapper dataset of complete calibrated endoscopy procedures](https://www.nature.com/articles/s41597-023-02564-7)_). The same model colonoscope, video processor, and light source were used to record Endomapper as were used for C3VD. I suspect the parameters are very similar to those for our system.

**Comment by Ruyi-Zha** [comment]
Thanks for the clarification. Cheers.
