### ISSUE TITLE
Undistort image and depth

### ISSUE THREAD

**Issue by lofrienger** [DurrLab/C3VD#15]
Hi C3VD authors, really impressive work! 

As discussed in the issue #2, you have provided parameters for undistort image with pinhole camera. I have tried with the below code
![image](https://github.com/DurrLab/C3VD/assets/43271256/6ead7be5-e1d1-424e-868d-4b77f8b47f3b)
and get the result like:
![image](https://github.com/DurrLab/C3VD/assets/43271256/28a2db2e-0474-46a7-93e3-d9f424955904)
It seems the image borders have been cropped after the undistortion. 
Is my code correct and is this result as expected? 

Could you please also share reference implementation or give me some hints for undistort images as presented in your paper?

**Comment by tbobrow1** [comment]
Hi @lofrienger! I am happy to hear that you are finding the dataset to be useful for your work. I am happy to assist you with uncertainties about the camera modeling.

In my experience, the pinhole camera model is not capable of modeling the peripheral field of view for cameras with severe fisheye distortion, such as in the colonoscope. It does work well for the center of the field-of-view, where distortions are much less severe. The undistorted frame in the image you posted is the expected result. If you want an undistorted image that includes all of the pixels, you can refine your camera matrix using the  _cv.getOptimalNewCameraMatrix()_ function with the _alpha_ parameter set equal to 1.  I've included sample code below and an image of the expected output. Notice that the corners of the checkerboard in the last image still exhibit some signs of distortion.

We do not do any image undistortion for the images in the paper. All of the rendering is implemented using the spherical camera model presented in [this paper](https://rpg.ifi.uzh.ch/docs/IROS06_scaramuzza.pdf), which accurately models wide field-of-view camera systems. You can find my implementation of the forward and backward projection functions [here](https://github.com/DurrLab/C3VD/blob/c7693be197176359456cc777faacd37507bbd3de/render/Render.cu#L68C14-L68C14) and [here](https://github.com/DurrLab/C3VD/blob/c7693be197176359456cc777faacd37507bbd3de/render/Render.cu#L46). This model is also what is used for fisheye cameras in the Matlab Camera Calibration Toolbox.

I hope this helps!

![sample](https://github.com/DurrLab/C3VD/assets/38167185/70754f7f-dd1c-4ea4-8315-deed4bb4309a)

```python
import cv2
import numpy as np
import matplotlib.pyplot as plt

# Read image
img = cv2.imread("frames/17.tiff");

# Pinhole camera params
K = np.array([[802.319,0,668.286],[0,801.885,547.733],[0,0,1]])
D = np.array([-0.42234,0.10654,0,0])
h,w = img.shape[:2]

# Undistort valid pixels
img_undistort = cv2.undistort(img, K, D, None, None)

# Undistort all pixels
K_new, roi = cv2.getOptimalNewCameraMatrix(K, D, (w,h), 1, (w,h))
img_undistort_a1 = cv2.undistort(img, K, D, None, K_new)

# Plot
plt.subplot(1,3,1)
plt.imshow(cv2.cvtColor(img,cv2.COLOR_BGR2RGB))
plt.title('Raw Image')
plt.axis('off')

plt.subplot(1,3,2)
plt.imshow(cv2.cvtColor(img_undistort,cv2.COLOR_BGR2RGB))
plt.title('Undistorted')
plt.axis('off')

plt.subplot(1,3,3)
plt.imshow(cv2.cvtColor(img_undistort_a1,cv2.COLOR_BGR2RGB))
plt.title('Undistorted | Alpha=1')
plt.axis('off')

plt.show()
```
