### ISSUE TITLE
Inquiry Regarding Paper Size for Calibration Grid Used in Your Study

### ISSUE THREAD

**Issue by liuyq055** [DurrLab/C3VD#17]
Could you kindly provide the dimensions of the paper on which the calibration grid was printed for your study? It is important for us to know the overall size of the paper, rather than the dimensions of the individual grid cells, to ensure the accuracy of our ongoing research.
As shown in the figure.
Thank you very much for your assistance and for the insights provided by your research.
![3](https://github.com/DurrLab/C3VD/assets/130023289/14ab605c-838a-4826-ae1c-d6a90d3b9fa0)

**Comment by tbobrow1** [comment]
@liuyq055 The checkerboard was printed on 8.5" x 11" printer paper, and the blank white edges of the paper were manually cut off before the target was taped to the lab bench. We did not measure the size of the cut target before taping it, though, knowing the squares have 10 mm sides, you could estimate the full size of the target, including the white border.

**Comment by liuyq055** [comment]
Thank you.

**Comment by liuyq055** [comment]
Certainly, could you please provide the physical focal length or sensor size information for the Olympus colonoscope? Thank you very much.

**Comment by tbobrow1** [comment]
Unfortunately, we do not know the focal length or sensor size. This information is not published by Olympus, and we are unable to access the internal components of the scope to take measurements.

**Comment by liuyq055** [comment]
Thank you.
