### ISSUE TITLE
Preprocess Code and 3d Model

### ISSUE THREAD

**Issue by Siwensun** [DurrLab/C3VD#4]
Hello @tbobrow1,

Thank you for releasing the C3VD dataset. It is an excellent contribution that will undoubtedly benefit the community.

However, I've noticed that the registration and rendering code are not currently available in this repo. Additionally, the link to download the 3D model files on the project website seems to be broken or inaccessible.

Could you please help address these concerns and provide guidance on how to access the necessary code and files? Your assistance would be greatly appreciated.

Thank you!

**Comment by tbobrow1** [comment]
Hi @Siwensun ,

I am glad that you have found the dataset to be useful! Thank you for pointing out the broken link for the "full_model_under_review.obj". I will reupload the file and fix the link. This file is just a combination of the other model files in a single file, so feel free to use the other models until I have an opportunity to correct the link.

We planned to release the code at the time of publication, but peer review is taking longer than expected. I will have the source files uploaded in the next few days so that you can access/use them. I'll tag you here once I have everything pushed to the repo.

Thanks for reaching out. Let me know if I can be helpful in any other way.

**Comment by Siwensun** [comment]
Appreciate your quick response.

**Comment by ifried01** [comment]
Hi @tbobrow1,

Thank you for creating and releasing the C3VD dataset. It is such a great resource for research.

Following up on Siwensun's question about the rendering and registration code: do you have an idea of when the code will be available? I was hoping to use the rendering code to try and create some novel depth maps in the OBJ models in a manner that is identical to the depth maps that already exist in the dataset.

Thank you!

**Comment by tbobrow1** [comment]
Hi @ifried01 happy to hear that the dataset has been helpful for you. I have added a user interface and a few other additions to the code to make it more user-friendly. I plan to finish these edits this afternoon, and I can push everything to the repo.

Are you looking to render synthetic images with ground truth depth? I planned to release the manual alignment/registration/ground truth rendering code, but this doesn't include the code I used to render synthetic images for training our depth estimation network. I could factor this code in if you want to use it, but it will take me some more time to clean up. Let me know if this is what you are looking for.

**Comment by ifried01** [comment]
Thanks for the quick reply @tbobrow1 !

Yes, I was hoping to render synthetic depth images. I was just wondering if it'd be part of the code release, but that's not a problem. I will try and implement this myself for now using the information from the paper.

Let me know when you plan to post the manual alignment/registration code. Looking forward to it!

**Comment by tbobrow1** [comment]
@ifried01 I just pushed all the code for the alignment GUI and ground truth rendering modules. I have a few more edits to make to the registration code before I push it. Let me know if you run into any challenges with building it. I have yet to try building on a fresh install of Ubuntu, so there may be additional dependencies that I am forgetting. I am happy to help troubleshoot any problems.

**Comment by ifried01** [comment]
Thank you!

**Comment by tbobrow1** [comment]
@Siwensun - I have uploaded the full 3D model file. I will push a download link to the dataset page tomorrow. Thanks for your patience.
