### ISSUE TITLE
Units of the camera pose

### ISSUE THREAD

**Issue by LeonBP** [DurrLab/C3VD#6]
Hello, thank you for uploading this dataset. I'm trying to use it to estimate camera pose.

My question is if the camera poses are measured in millimeters. Other parts of the dataset are in millimeters but I need confirmation that the camera poses are also in millimeters.

Thank you very much

**Comment by tbobrow1** [comment]
Hi @LeonBP , you are correct. The camera pose units are in millimeters. I will add a note to the webpage to clarify this. Let me know if you need assistance with using the dataset with your project.
