### ISSUE TITLE
how to undistort normal

### ISSUE THREAD

**Issue by howardchina** [DurrLab/C3VD#8]
I try to model the camera as a pinhole camera model.
Then I need to undistort the RGB, Depth and Normal.
It is easy for my to process the RGB and Depth.
But how to deal with Normal?

**Comment by tbobrow1** [comment]
@howardchina: Instead of undistorting the surface normals, some users have computed surface normals from the undistorted depth maps. These can be computed by the differential or cross-product with respect to neighboring pixels.

**Comment by tbobrow1** [comment]
Sorry, I didn't mean to close this. Let me know if this makes sense.

**Comment by howardchina** [comment]
@tbobrow1 Hi, I find the solution!
The color mapping problem is fixed by compare the histogram of xyz with your color mapping.
After I draw histograms, I found the my histogram is almost symmetrical to yours.
So I just `normal = 0 - normal`, then my color mapping is almost the same to yours.

I was concerned about if your intinsic maybe different to mine so our normals can be different.
Thank to histogram. Our difference are just the sign of the normal.

**Comment by howardchina** [comment]
For your convenience. 
My depth2normal function is provided in https://github.com/howardchina/depth2normal4c3vd/blob/main/normal.ipynb.

I provide 2 versions of depth2normal functions that collected from others' repos. Both provide the same result.

**Comment by tbobrow1** [comment]
Glad you found a solution, @howardchina. Depending on the coordinate system for the camera intrinsics you are using, you may have to do a change of basis to make the normals match what is used in the paper. To fix the normals at occluded regions, you could use the ground truth occlusion frames to identify edge discontinuities.

Thanks for sharing the depth2normal functions. I may upload these as helper functions in the repo when I push my next update. I will also try to render normals with the pinhole camera intrinsics to avoid having to compute your own. This may take me a while to get to, so the depth2normals workaround should work nicely for now.
